FROM openmindagi/riva-speech:2.17.0-l4t-aarch64 AS base

RUN apt-get update && \
    apt-get install -y curl python3-pyaudio pulseaudio pulseaudio-utils alsa-utils libasound2t64 libasound2-plugins netcat-openbsd && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN pip install pyaudio==0.2.14 websockets==16.0 numpy==1.26.4 opencv-python==4.11.0.86 requests==2.32.5 google==3.0.0 eclipse-zenoh==1.7.2 pycdr2==1.0.0 av==16.1.0 vulture==2.14 openai==2.24.0 protobuf==6.33.5
RUN pip uninstall -y wandb && pip install wandb==0.18.7

RUN mkdir /app

COPY ./src/om1_speech /app/om1_speech
COPY ./src/om1_utils /app/om1_utils
COPY ./src/zenoh_msgs /app/zenoh_msgs

COPY ./docker/scripts/start_riva.sh /app/start_riva.sh

RUN chmod +x /app/start_riva.sh

CMD ["/app/start_riva.sh"]
